name: fw_app_workspace
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  build_runner: ^2.4.7
  melos: ^3.1.0
dependencies:
  digit_data_model: 1.0.4-dev.7
  dart_mappable: ^4.2.0
  mason: ^0.1.0-dev.52



