name: digit_maps
description: "Open Source Digit Maps to populate households and search by proximity"
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  auto_route: ^8.1.3
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  latlong2: ^0.9.1
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  flutter_bloc: ^8.1.1
  retrofit: ^4.4.2
  dio: ^5.4.3+1
  collection: ^1.16.0
  flutter_map_tile_caching: ^9.0.0
  geolocator: ^10.1.0
  flutter_map_location_marker: ^8.0.5
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  retrofit_generator: ^8.2.1
